from PySide6.QtCore import QCoreApplication


def translation_sources():
    # WeatherDescriptions 上下文的所有字符串
    QCoreApplication.translate("WeatherDescriptions", "Sunny")
    QCoreApplication.translate("WeatherDescriptions", "Clear")
    QCoreApplication.translate("WeatherDescriptions", "Mainly Sunny")
    QCoreApplication.translate("WeatherDescriptions", "Mainly Clear")
    QCoreApplication.translate("WeatherDescriptions", "Partly Cloudy")
    QCoreApplication.translate("WeatherDescriptions", "Cloudy")
    QCoreApplication.translate("WeatherDescriptions", "Foggy")
    QCoreApplication.translate("WeatherDescriptions", "Rime Fog")
    QCoreApplication.translate("WeatherDescriptions", "Light Drizzle")
    QCoreApplication.translate("WeatherDescriptions", "Drizzle")
    QCoreApplication.translate("WeatherDescriptions", "Heavy Drizzle")
    QCoreApplication.translate("WeatherDescriptions", "Light Freezing Drizzle")
    QCoreApplication.translate("WeatherDescriptions", "Freezing Drizzle")
    QCoreApplication.translate("WeatherDescriptions", "Light Rain")
    QCoreApplication.translate("WeatherDescriptions", "Rain")
    QCoreApplication.translate("WeatherDescriptions", "Heavy Rain")
    QCoreApplication.translate("WeatherDescriptions", "Light Freezing Rain")
    QCoreApplication.translate("WeatherDescriptions", "Freezing Rain")
    QCoreApplication.translate("WeatherDescriptions", "Light Snow")
    QCoreApplication.translate("WeatherDescriptions", "Snow")
    QCoreApplication.translate("WeatherDescriptions", "Heavy Snow")
    QCoreApplication.translate("WeatherDescriptions", "Snow Grains")
    QCoreApplication.translate("WeatherDescriptions", "Light Showers")
    QCoreApplication.translate("WeatherDescriptions", "Showers")
    QCoreApplication.translate("WeatherDescriptions", "Heavy Showers")
    QCoreApplication.translate("WeatherDescriptions", "Light Snow Showers")
    QCoreApplication.translate("WeatherDescriptions", "Snow Showers")
    QCoreApplication.translate("WeatherDescriptions", "Thunderstorm")
    QCoreApplication.translate("WeatherDescriptions", "Light Thunderstorms With Hail")
    QCoreApplication.translate("WeatherDescriptions", "Thunderstorm With Hail")
